"""add url for apartment

Revision ID: 0a5f155405f2
Revises: 2b088440f2e4
Create Date: 2022-11-04 18:27:20.413909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5f155405f2'
down_revision = '2b088440f2e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'link')
    # ### end Alembic commands ###
