"""add query to subquery

Revision ID: 13ad40b01148
Revises: f437e7be9a94
Create Date: 2022-11-01 20:15:24.212728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ad40b01148'
down_revision = 'f437e7be9a94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
