"""fix types

Revision ID: 44e8a4e80700
Revises: 0a5f155405f2
Create Date: 2022-11-04 19:14:26.627796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e8a4e80700'
down_revision = '0a5f155405f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment', 'walls',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment', 'kitchen_area',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment', 'has_balcony',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('apartment', 'distance_to_metro',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment', 'quality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment', 'm2price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('apartment', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment', 'm2price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('apartment', 'quality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apartment', 'distance_to_metro',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment', 'has_balcony',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('apartment', 'kitchen_area',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment', 'walls',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
