"""fix tables

Revision ID: 747560d2a5cb
Revises: c29ba8521450
Create Date: 2022-11-05 16:08:50.210886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747560d2a5cb'
down_revision = 'c29ba8521450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
