"""change id to guid in users table

Revision ID: 772040219724
Revises: a9eebcf3d60f
Create Date: 2022-10-30 09:46:19.252169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '772040219724'
down_revision = 'a9eebcf3d60f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_user_id', table_name='user')
    op.create_index(op.f('ix_user_guid'), 'user', ['guid'], unique=True)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_guid'), table_name='user')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'guid')
    # ### end Alembic commands ###
