"""rebuild migrations

Revision ID: 846146bb0e5e
Revises: 
Create Date: 2022-11-06 08:15:51.918626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '846146bb0e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('input_file', sa.String(), nullable=False),
    sa.Column('output_file', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_query_guid'), 'query', ['guid'], unique=True)
    op.create_table('user',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_guid'), 'user', ['guid'], unique=True)
    op.create_table('sub_query',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('query_guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['query_guid'], ['query.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_sub_query_guid'), 'sub_query', ['guid'], unique=True)
    op.create_table('apartment',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('lon', sa.Numeric(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('walls', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('apartment_area', sa.Integer(), nullable=False),
    sa.Column('kitchen_area', sa.Integer(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('distance_to_metro', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('m2price', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('input_apartments_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('standart_object_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('analogs_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('selected_analogs_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('output_apartments_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['analogs_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['input_apartments_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['output_apartments_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['selected_analogs_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['standart_object_guid'], ['sub_query.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_apartment_guid'), 'apartment', ['guid'], unique=True)
    op.create_table('adjustment',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apartment_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('trade', sa.Float(), nullable=False),
    sa.Column('price_trade', sa.Numeric(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=False),
    sa.Column('price_floor', sa.Numeric(), nullable=False),
    sa.Column('apt_area', sa.Float(), nullable=False),
    sa.Column('price_area', sa.Numeric(), nullable=False),
    sa.Column('kitchen_area', sa.Float(), nullable=False),
    sa.Column('price_kitchen', sa.Numeric(), nullable=False),
    sa.Column('has_balcony', sa.Float(), nullable=False),
    sa.Column('price_balcony', sa.Numeric(), nullable=False),
    sa.Column('distance_to_metro', sa.Float(), nullable=False),
    sa.Column('price_metro', sa.Numeric(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('price_final', sa.Numeric(), nullable=False),
    sa.Column('analog_calculated_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('analog_user_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pool_calculated_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pool_user_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['analog_calculated_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['analog_user_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['apartment_guid'], ['apartment.guid'], ),
    sa.ForeignKeyConstraint(['pool_calculated_guid'], ['sub_query.guid'], ),
    sa.ForeignKeyConstraint(['pool_user_guid'], ['sub_query.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_adjustment_guid'), 'adjustment', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustment_guid'), table_name='adjustment')
    op.drop_table('adjustment')
    op.drop_index(op.f('ix_apartment_guid'), table_name='apartment')
    op.drop_table('apartment')
    op.drop_index(op.f('ix_sub_query_guid'), table_name='sub_query')
    op.drop_table('sub_query')
    op.drop_index(op.f('ix_user_guid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_query_guid'), table_name='query')
    op.drop_table('query')
    # ### end Alembic commands ###
