"""add fk for sub_query

Revision ID: 953f354372dd
Revises: 86567c806fa2
Create Date: 2022-11-01 20:05:20.492602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '953f354372dd'
down_revision = '86567c806fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adjustment', sa.Column('sub_query_guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'adjustment', 'sub_query', ['sub_query_guid'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adjustment', type_='foreignkey')
    op.drop_column('adjustment', 'sub_query_guid')
    # ### end Alembic commands ###
