"""fix types

Revision ID: a033cd13d1e1
Revises: 747560d2a5cb
Create Date: 2022-11-05 19:23:05.469539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a033cd13d1e1'
down_revision = '747560d2a5cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
