"""add analogs to subquery

Revision ID: a4c6948a7882
Revises: 13ad40b01148
Create Date: 2022-11-01 20:29:51.911760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c6948a7882'
down_revision = '13ad40b01148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
