"""add one-to-one relationship with apartment

Revision ID: c29ba8521450
Revises: 44e8a4e80700
Create Date: 2022-11-05 15:55:06.035306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c29ba8521450'
down_revision = '44e8a4e80700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adjustment', sa.Column('apartment_guid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'adjustment', 'apartment', ['apartment_guid'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adjustment', type_='foreignkey')
    op.drop_column('adjustment', 'apartment_guid')
    # ### end Alembic commands ###
