"""add apartment table

Revision ID: c9a642144513
Revises: 772040219724
Create Date: 2022-10-30 10:50:17.964911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9a642144513'
down_revision = '772040219724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('segment', sa.Enum('NEW', 'MODERN', 'OLD', name='segment'), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('walls', sa.Enum('BRICK', 'PANEL', 'MONOLITH', name='walls'), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('apt_area', sa.Integer(), nullable=False),
    sa.Column('kitchen_area', sa.Integer(), nullable=False),
    sa.Column('has_balcony', sa.Boolean(), nullable=False),
    sa.Column('distance_to_metro', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Enum('NO_FINISH', 'ECONOM', 'IMPROVED', name='quality'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_apartment_guid'), 'apartment', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apartment_guid'), table_name='apartment')
    op.drop_table('apartment')
    # ### end Alembic commands ###
