"""add lan, lon to apartment table

Revision ID: cab84b0ee0df
Revises: 4465ac864230
Create Date: 2022-10-30 15:39:11.939065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab84b0ee0df'
down_revision = '4465ac864230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('lat', sa.Numeric(), nullable=False))
    op.add_column('apartment', sa.Column('lon', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'lon')
    op.drop_column('apartment', 'lat')
    # ### end Alembic commands ###
