"""add fk for sub_query

Revision ID: f437e7be9a94
Revises: 953f354372dd
Create Date: 2022-11-01 20:07:04.653737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f437e7be9a94'
down_revision = '953f354372dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('sub_query_guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'apartment', 'sub_query', ['sub_query_guid'], ['guid'])
    op.add_column('manual_adjustment', sa.Column('sub_query_guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'manual_adjustment', 'sub_query', ['sub_query_guid'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manual_adjustment', type_='foreignkey')
    op.drop_column('manual_adjustment', 'sub_query_guid')
    op.drop_constraint(None, 'apartment', type_='foreignkey')
    op.drop_column('apartment', 'sub_query_guid')
    # ### end Alembic commands ###
